### PR TITLE
Move to peaceiris/actions-gh-pages action

### PR DESCRIPTION
**Pull request by CAMOBAP**

### CODE REVIEW

**Comment by ronaldtse** [comment]
@CAMOBAP795 could you help fix this? Seems that `nvm.sh` is the problem on Ubuntu...

**Comment by CAMOBAP** [comment]
@ronaldtse in my list, here is dedicated thicket reported to it https://github.com/metanorma/metanorma-linux-setup/issues/23

**Comment by ronaldtse** [comment]
@CAMOBAP795 it seems that Ruby 2.4 must use 0.0.7.4, but Ruby 2.5 and 2.6 do not have alternatives.

According to this issue we can lock to 0.0.7.2:
https://github.com/discordrb/discordrb/issues/604#issuecomment-475913239

**Comment by CAMOBAP** [comment]
@ronaldtse 0.0.7.2 looks working 

```
In Gemfile:
  metanorma-cli was resolved to 1.2.10.1, which depends on
    metanorma-acme was resolved to 1.4.4, which depends on
      metanorma-standoc was resolved to 1.3.21, which depends on
        relaton-iev was resolved to 0.1.3, which depends on
          relaton was resolved to 0.10.1, which depends on
            relaton-un was resolved to 0.1.0, which depends on
              http-cookie was resolved to 1.0.3, which depends on
                domain_name was resolved to 0.5.20190701, which depends on
                  unf was resolved to 0.1.4, which depends on
                    unf_ext
```

I think it make sense to restrict it on `relaton-un` till it will be fixed, @ronaldtse make sense?

**Comment by ronaldtse** [comment]
> I think it make sense to restrict it on relaton-un till it will be fixed, @ronaldtse make sense?

Makes perfect sense. Can you make PR on relaton-un, also add a comment in `relaton-un.gemspec` that this is temporary? (@andrew2net can you help merge?) Thanks!

**Comment by CAMOBAP** [comment]
@ronaldtse PR done https://github.com/relaton/relaton-un/pull/2

**Comment by CAMOBAP** [comment]
Merging to test gh-pages publishing

**Pull request merged**
