### PR TITLE
metanorma/metanorma-docker#39 Allow to override docker image

### PR DESCRIPTION
**Pull request by CAMOBAP**
- metanorma/metanorma-docker#39

### CODE REVIEW

**Comment by ronaldtse** [comment]
@andrew2net please help fix this: error trace:

```ruby
fetching ISO 19136...
1702#<Thread:0x0000000003706298@/home/travis/build/metanorma/mn-itu-docs/vendor/bundle/ruby/2.5.0/gems/relaton-bib-0.2.4/lib/relaton_bib/workers_pool.rb:17 run> terminated with exception (report_on_exception is true):
1703/home/travis/build/metanorma/mn-itu-docs/vendor/bundle/ruby/2.5.0/gems/relaton-iso-0.5.2/lib/relaton_iso/scrapper.rb:309:in `fetch_title': undefined method `text' for nil:NilClass (NoMethodError)
1704	from /home/travis/build/metanorma/mn-itu-docs/vendor/bundle/ruby/2.5.0/gems/relaton-iso-0.5.2/lib/relaton_iso/scrapper.rb:141:in `block in fetch_titles_abstract'
1705	from /home/travis/build/metanorma/mn-itu-docs/vendor/bundle/ruby/2.5.0/gems/relaton-iso-0.5.2/lib/relaton_iso/scrapper.rb:134:in `each'
1706
```

**Comment by andrew2net** [comment]
> ```ruby
> fetching ISO 19136...
> 1702#<Thread:0x0000000003706298@/home/travis/build/metanorma/mn-itu-docs/vendor/bundle/ruby/2.5.0/gems/relaton-bib-0.2.4/lib/relaton_bib/workers_pool.rb:17 run> terminated with exception (report_on_exception is true):
> 1703/home/travis/build/metanorma/mn-itu-docs/vendor/bundle/ruby/2.5.0/gems/relaton-iso-0.5.2/lib/relaton_iso/scrapper.rb:309:in `fetch_title': undefined method `text' for nil:NilClass (NoMethodError)
> 1704	from /home/travis/build/metanorma/mn-itu-docs/vendor/bundle/ruby/2.5.0/gems/relaton-iso-0.5.2/lib/relaton_iso/scrapper.rb:141:in `block in fetch_titles_abstract'
> 1705	from /home/travis/build/metanorma/mn-itu-docs/vendor/bundle/ruby/2.5.0/gems/relaton-iso-0.5.2/lib/relaton_iso/scrapper.rb:134:in `each'
> 1706
> ```

@CAMOBAP795 this issue in `relaton-iso` was solved in v0.5.4.  Please use the last version.

**Comment by ronaldtse** [comment]
@andrew2net the 0.5.4 version of `relaton` gem isn't released, could you help do so? Thanks.

**Comment by ronaldtse** [comment]
@andrew2net thanks!

**Comment by ronaldtse** [comment]
@opoudjis compilation is failing due to metanorma-itu. Can you please help fix this? Thanks!

```sh
bundler: failed to load command: metanorma (/Users/me/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bin/metanorma)
Errno::ENOENT: No such file or directory @ rb_sysopen - /Users/me/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/metanorma-itu-0.2.1/lib/asciidoctor/itu/i18n-en.yaml
  /Users/me/.rbenv/versions/2.5.1/lib/ruby/2.5.0/psych.rb:497:in `initialize'
  /Users/me/.rbenv/versions/2.5.1/lib/ruby/2.5.0/psych.rb:497:in `open'
  /Users/me/.rbenv/versions/2.5.1/lib/ruby/2.5.0/psych.rb:497:in `load_file'
  /Users/me/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/metanorma-itu-0.2.1/lib/asciidoctor/itu/converter.rb:162:in `load_yaml'
  /Users/me/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/metanorma-standoc-1.3.1/lib/asciidoctor/standoc/i18n.rb:26:in `i18n_init'
  /Users/me/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/metanorma-standoc-1.3.1/lib/asciidoctor/standoc/base.rb:106:in `init'
  /Users/me/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/metanorma-itu-0.2.1/lib/asciidoctor/itu/converter.rb:57:in `document'
  /Users/me/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/metanorma-standoc-1.3.1/lib/asciidoctor/standoc/utils.rb:137:in `convert'
  /Users/me/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/asciidoctor-1.5.8/lib/asciidoctor/document.rb:1190:in `convert'
  /Users/me/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/asciidoctor-1.5.8/lib/asciidoctor.rb:1521:in `convert'
  /Users/me/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/metanorma-0.3.14/lib/metanorma/input/asciidoc.rb:8:in `process'
  /Users/me/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/metanorma-itu-0.2.1/lib/metanorma/itu/processor.rb:26:in `input_to_isodoc'
```

**Comment by opoudjis** [comment]
Checked in a missing file in metanorma-itu

**Pull request merged**
