### PR TITLE
Converted STL manual

### PR DESCRIPTION
**Pull request by anermina**

### CODE REVIEW

**Comment by ronaldtse** [comment]
To be compiled and merged when ready (@opoudjis ).

**Comment by opoudjis** [comment]
Drawing attention @anermina to the asciidoctor formatting faults reported:

The table ".RPE-LTP bitstream format for each 20 ms speech frame." had blown up because of one typo: `&` instead of `^|`

The reference `ITU-T P.56:1989` cannot be fetched by Relaton.

I've fixed:

````
asciidoctor: WARNING: <stdin>: line 6368: section title out of sequence: expected level 2, got level 3
````

and the faulty reference: "ITU-T G.72)" to ITU-T G.722.

Anchors are not allowed to contain colons, but Metanorma is automatically fixing these to underscores.

The bibliography ordering is quite random, because Metanorma is insisting in putting the ITU references first, in sorted order, and it's doing the right thing in doing so. The numbers suggested in data entry (e.g. `[[[G.722,(42)ITU-T G.722]]]`) are not being overridden; but it does seem that the ordering the document had in data entry did not follow the same ordering we imposed anyway. I can override the numbering provided in data entry, but I don't want to yet.

The document is now working with these fixes, but decide what you want to do with the bibliography: you renumber the manual numbers, or make me override them, or make me ignore re-sorting the entries. Yes, of course I would prefer the first :-)  And we MUST NOT do the third—Metanorma is meant to be making documents more consistent, not perpetuating slapdash work from document authors...

**Comment by anermina** [comment]
Thanks @opoudjis ! I've renumbered bibliography entries.

**Review by opoudjis — APPROVED** [review]

**Comment by ronaldtse** [comment]
Thanks guys!

**Pull request merged**
