### PR TITLE
ITU G.650 minor changes

### PR DESCRIPTION
**Pull request by anermina**
- Separated an image into two sub-figures and changed cross-referencing in accordance to the new anchors.
- Added one missing space.
- Replaced false dashes (which were causing hash instead of dash generation in PDF) with regular ones.

### CODE REVIEW

**Comment by ronaldtse** [comment]
@CAMOBAP795 can you have a look here? The build is failing due to:

```
[relaton-iso] ("ISO 19136") fetching...
164
bundler: failed to load command: metanorma (/usr/local/bundle/bin/metanorma)
165
NoMethodError: undefined method `empty?' for nil:NilClass
166
  /usr/local/bundle/gems/relaton-iso-0.11.0/lib/relaton_iso/hit_collection.rb:35:in `block in to_all_parts'
167
  /usr/local/bundle/gems/relaton-iso-0.11.0/lib/relaton_iso/hit_collection.rb:35:in `select'
168
  /usr/local/bundle/gems/relaton-iso-0.11.0/lib/relaton_iso/hit_collection.rb:35:in `to_all_parts'
169
  /usr/local/bundle/gems/relaton-iso-0.11.0/lib/relaton_iso/iso_bibliography.rb:159:in `isobib_results_filter'
170
```

**Comment by ronaldtse** [comment]
(Thanks @anermina , the content is good!)

**Comment by CAMOBAP** [comment]
@anermina please ignore the issue on windows it will be fixed on next release https://github.com/metanorma/chocolatey-metanorma/issues/42

I have restarted the workflows and builds looks good

**Comment by anermina** [comment]
Thanks @CAMOBAP795 ! I'll have that on my mind.

**Pull request merged**
