### PR TITLE
Use new site generation functionality in metanorma-cli

### PR DESCRIPTION
**Pull request by ronaldtse**
This may or may not be immediately useable because packed-mn may not yet include the newest metanorma-cli.

@CAMOBAP could you please help make the GHA flow work and apply to all our mn-*-* repos? Thanks!

### CODE REVIEW

**Comment by ronaldtse** [comment]
@camobap wow only the "test-docker" workflow is failing, all the rest are passing! Leaving the docker one in your good hands!

**Comment by ronaldtse** [comment]
@CAMOBAP the Windows build fails due to bundler not installing the Git CLI gem:
```
C:/Users/RUNNER~1/AppData/Local/Temp/ocr4BB9.tmp/lib/ruby/2.6.0/bundler/source/git/git_proxy.rb:235:in `allowed_in_path': The git source https://github.com/metanorma/metanorma-cli is not yet checked out. Please run `bundle install` before trying to start your application (Bundler::GitError)
```

Can you help here?

**Comment by ronaldtse** [comment]
Since @opoudjis is releasing new metanorma-cli tomorrow we probably don't need to fix the above comment.

**Comment by CAMOBAP** [comment]
> Since opoudjis is releasing new metanorma-cli tomorrow we probably don't need to fix the above comment.

I think we need to check because packed-mn looks broken on windows

**Comment by ronaldtse** [comment]
@CAMOBAP also need your help with this. Thanks!

**Pull request merged**
